#--------------------------#
# Central parameters       #
#--------------------------#
aligner: diamond # blast / diamond / mmseqs2
gapseq_repo: https://github.com/jotech/gapseq.git
gapseq_branch: master
gapseq_seqDB: $curdir/gapseq/dat/seq
gapseq_seqDBversion: latest # 'latest' or one of the zenodo record IDs (https://doi.org/10.5281/zenodo.10047603)

#--------------------------#
# Parameters "gapseq find" #
#--------------------------#
find_threads: 4
find_mem: 12 # Gb
find_time: 30m # 'm' for minutes
find_b: 200 # bitscore cutoff

#---------------------------#
# Parameter "gapseq draft"  #
#---------------------------#
draft_threads: 1
draft_mem: 3 # Gb
draft_time: 10m # 'm' for minutes
draft_u: 200
draft_l: 100

#---------------------------#
# Parameter "gapseq medium" #
#---------------------------#
medium_c: "cpd00007:0"

#---------------------------#
# Parameter "gapseq fill"   #
#---------------------------#
fill_threads: 1
fill_mem: 3 # Gb
fill_b: 100
fill_time: 45m # 'm' for minutes
fill_mingr: 0.001

